### ISSUE TITLE
lat/lon priority not used or not working

### ISSUE THREAD

**Issue by spinarial** [komoot/photon#336]
Hello,
I'm trying to limit the search by country using lat and lon coordinate in the center of it to get the best matching result. Howewher the expected result end up in the last entry of the data-set or not in the data-set at all.

Let's take the city "Dijon" in "France" for the example. By using the keyword "dij" and the coordinates lat=47.0780167&lon=2.3282636 (approximativaly the center of the country).
[http://photon.komoot.de/api/?q=dij&lat=47.0780167&lon=2.3282636](http://photon.komoot.de/api/?q=dij&lat=47.0780167&lon=2.3282636)
I get the result i want but in the last results.

Same things with "Paris" (same coordinates)
[http://photon.komoot.de/api/?q=par&lat=47.0780167&lon=2.3282636](http://photon.komoot.de/api/?q=par&lat=47.0780167&lon=2.3282636)

Am i doing something wrong ?

**Comment by kurko** [comment]
@spinarial AFAIK, this is fixed in v0.3, but it's not deployed on komoot's servers yet (I have tried it in my own instance and it worked for a case in the UK).

**Comment by karussell** [comment]
Thanks for confirming this. Will close here now.

**Comment by alexandervlpl** [comment]
Using self-hosted Photon 0.3.1. This is still not working as expected for me. Setting a latitude/longitude in the United States doesn't seem to give any priority to US results. Example:

http://photon.komoot.de/api?q=berlin&lat=39.828&lon=-98.580
